version: '3.9'

services:
  web:
    build:
      context: ../
      dockerfile: docker/images/apache/Dockerfile
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - ./configuration/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./configuration/apache/site.conf:/usr/local/apache2/conf/extra/site.conf
      - ../:/var/www/html
    networks:
      - local

  php8:
    build:
      context: ../
      dockerfile: docker/images/php/8.2/Dockerfile
      target: php_8_fpm
      args:
        HOST_USER_ID: ${DOCKER_HOST_USER_ID}
        HOST_GROUP_ID: ${DOCKER_HOST_GROUP_ID}
    working_dir: /var/www/html
    environment:
      PHP_IDE_CONFIG: serverName=webshop.loc
      XDEBUG_HOST: host.docker.internal
      XDEBUG_PORT: ${PHP_XDEBUG_PORT}
    volumes:
      - ../:/var/www/html
      - ${HOME}/.ssh:/home/web/.ssh
    expose:
      - 9000
    networks:
      - local

  mysql:
    hostname: mysql
    image: percona/percona-server:5.7.26
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./configuration/mysql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
      - mysql-log:/var/log/mysql
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  mysql:
  mysql-log:
